In [1]:
# Load library
import numpy as np

In [2]:
# Create matrix
matrix = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])

In [3]:
# Flatten matrix
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
matrix.reshape(1, -1)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [5]:
# Create one matrix
matrix_a = np.array([[1, 2],
[3, 4]])

In [6]:
# Create a second matrix
matrix_b = np.array([[5, 6],
[7, 8]])

In [7]:
# Create a list of matrices
matrix_list = [matrix_a, matrix_b]

In [8]:
# Flatten the entire list of matrices
np.ravel(matrix_list)

array([1, 2, 3, 4, 5, 6, 7, 8])